micronaut:
  application:
    name: complete
datasources:
  default:
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none